pipeline:
  checkout:
    image: docker.moxa.online/build/base:stretch
    commands:
      - git checkout --track -b ${DRONE_BRANCH} origin/${DRONE_BRANCH}
      - git merge ${CI_COMMIT_BRANCH}
    when:
      event:
        exclude: [ pull_request, tag ]
      branch:
        exclude: [ master ]
      local: false

  restore_cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - .yarn-amd64-stretch
    when:
      event: [ push, pull_request ]
    volumes:
      - /var/tmp:/cache

  upload_doc:
    image: docker.moxa.online/build/nodejs:stretch
    pull: true
    commands: |
      . /root/.bashrc;
      useradd -ms /bin/bash docser;
      apt-get update && apt-get install -y rsync;
      sed -i "s#baseUrl:.*#baseUrl: '/',#" ./website/siteConfig.js;
      yarn;
      yarn create:version develop;
      cd website && yarn build;
      su docser -c "rsync -a build/developer-docs/ /mnt/docs";
      echo -e "\033[0;32mSUCCESS!!\033[0m";
    when:
      event: [ push, pull_request ]
    volumes:
      - /mnt/storage/repo/static/developer-docs:/mnt/docs:z

  rebuild_cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - .yarn-amd64-stretch
    when:
      event: [ push, pull_request ]
    volumes:
      - /var/tmp:/cache
